### ISSUE TITLE
There is no overall license information

### ISSUE THREAD

**Issue by stefanha** [bytedance/libnvmf#1]
Please state the overall license of the library so that application developers know under what terms they can use the library and distro packagers can correctly classify the library.

Typically there is a COPYING or COPYING.LIB file in the root of the source tree. GitHub should automatically detect common licenses and show them with your project's metadata.

**Comment by pizhenwei** [comment]
Add COPYING file in this commit. Thanks.
https://github.com/bytedance/libnvmf/commit/af57b7d4a1422728ddb36f07f860cc8c6cacbe44
