### ISSUE TITLE
Please clarify copyright of slab, llist, buddy, etc

### ISSUE THREAD

**Issue by stefanha** [bytedance/libnvmf#2]
It's not clear to me whether slab, llist, buddy, etc are cleanroom reimplementations of these utilities from Linux or whether they incorporate code from Linux. The copyright header does not make it clear.
If the code was (partially) taken from another project like Linux, please keep the copyright headers. I think that's explicitly required by the GNU GPL license, for example.
If the code is a cleanroom reimplementation of these APIs from Linux, please indicate this in the copyright header so that it's readily apparent to anyone that needs to understand the license situation of the code.

**Comment by pizhenwei** [comment]
Fixed in commit af57b7d4a1422728ddb36f07f860cc8c6cacbe44. Thanks.
